spring.application.name=tp2

# URL del servicio MySQL y nombre de la DB
spring.datasource.url=jdbc:${DB_SUBPROTOCOL}://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}

# Datos del usuario de la DB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Registro de sentencias SQL
spring.jpa.show-sql=true

# Crea o Actualiza la DB
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect